# 예외처리가 필요한 이유

- 자바에서의 예외처리는 "프로그램의 비정상적인 종료를 막고, 상태를 정상상태로 유지하기 위함입니다."
- 예외를 처리하는 문법은 try-catch 문, try-catch-finally 문이 있습니다.

```
try {


} catch(Exception e){


}
```
- try-catch에서 예외가 발생하지 않을 경우 try 블록에 있는 모든 문장이 수행되어지고, try-catch문 이후의 문장이 수행되어집니다.
- try-catch에서 예외가 발생한 경우
  - try 블록 내에서 예외가 발생한 부분 이후의 문장들은 실행되지 않습니다.
  - catch 블록에 있는 모든 문장이 수행되어지고 try-catch 이후의 문장이 수행되어집니다.
    
 
```
// 예외가 발생하지 않은 경우
public class ExceptionVariable {

    public static void main(String[] args) {
        ExceptionVariable sample = new ExceptionVariable();
        sample.checkVariable();
    }

    private void checkVariable() {
        int[] intArr = new int[5];
        try{
            System.out.println(intArr[5]);
        }catch (Exception e){
            System.out.println(intArr.length);
        }
        System.out.println("finshCode");
    }
}


```

```
// 예외가 발생한 경우
public class ExceptionVariable2 {

    public static void main(String[] args) {
        ExceptionVariable2 sample = new ExceptionVariable2();
        sample.checkVariable();
    }

    private void checkVariable() {
        int[] intArr = new int[5];
        try{
            System.out.println("try 블럭 수행");
            System.out.println(intArr[6]);
        }catch (Exception e){
            System.out.println("catch 블럭 수행");
            System.out.println(intArr.length);
            System.out.println(e.getMessage());
        }
        System.out.println("블록 이후의 문장이 수행되어집니다.");
    }
}


```
또한 try 블록과 catch 블록은 분리되어져 있어서 변수의 선언을 주의해야한다.


```
=

public class ExceptionVariable3 {

    public static void main(String[] args) {
        ExceptionVariable3 sample = new ExceptionVariable3();
        sample.checkVariable();
    }

    private void checkVariable() {

        try{
            int[] intArr = new int[5];
            System.out.println("try 블럭 수행");
            System.out.println(intArr[6]);
        }catch (Exception e){
            System.out.println("catch 블럭 수행");
            System.out.println(intArr.length); // 변수를 찾을 수 없어서 에러발생. cannot find symbol
            System.out.println(e.getMessage());
        }
        System.out.println("블록 이후의 문장이 수행되어집니다.");
    }
}
```

그래서 아래와 같이 try 블럭 앞에 변수를 미리 선언해 놓는다.

```
package exception;

public class ExceptionVariable4 {

    public static void main(String[] args) {
        ExceptionVariable3 sample = new ExceptionVariable3();
        sample.checkVariable();
    }

    private void checkVariable() {
        int[] intArr = null; // 변수를 미리 선언합니다.
        try{
            intArr = new int[5];
            System.out.println("try 블럭 수행");
            System.out.println(intArr[6]);
        }catch (Exception e){
            System.out.println("catch 블럭 수행");
            System.out.println(intArr.length);
            System.out.println(e.getMessage());
        }
        System.out.println("블록 이후의 문장이 수행되어집니다.");
    }
}


```












